ALTER TABLE SERVICESLIST
 ADD CONSTRAINT FK_SERVICESLISTCAMPCARID
 FOREIGN KEY (CAMPCARID) REFERENCES CAMPINGCAR(CARID) ON DELETE CASCADE
 ADD CONSTRAINT FK_SERVICESLISTSERVCENTERID
 FOREIGN KEY (SERVCENTERID) REFERENCES CARSERVICECENTER(CENTERID) ON DELETE CASCADE
 ADD CONSTRAINT FK_SERVICESLISTRENTCOMPID
 FOREIGN KEY (RENTCOMPID) REFERENCES RENTALCOMPANY(COMPID) ON DELETE CASCADE
 ADD CONSTRAINT FK_SERVICESLISTCUSLICNUM
 FOREIGN KEY (CUSLICNUM) REFERENCES CUSTOMER(LICNUM) ON DELETE CASCADE;
