ALTER TABLE RENTLIST
 ADD CONSTRAINT FK_RENTLISTLICNUM
 FOREIGN KEY (CUSLICNUM) REFERENCES CUSTOMER(LICNUM) ON DELETE CASCADE
 ADD CONSTRAINT FK_RENTLISTRENTCOMPID
 FOREIGN KEY (RENTCOMPID) REFERENCES RENTALCOMPANY(COMPID) ON DELETE CASCADE
 ADD CONSTRAINT FK_RENTLISTCAMPCARID
 FOREIGN KEY (CAMPCARID) REFERENCES CAMPINGCAR(CARID) ON DELETE CASCADE;
