ALTER TABLE REQUIRESERVICELIST
 ADD CONSTRAINT FK_REQUIRESERVICELISTCUSLICNUM
 FOREIGN KEY (CUSLICNUM) REFERENCES CUSTOMER(LICNUM) ON DELETE CASCADE
 ADD CONSTRAINT FK_REQUIRESERVICELISTRENTALID
 FOREIGN KEY (RENTALID) REFERENCES RENTLIST(RENTALID) ON DELETE CASCADE;
