ALTER TABLE SERVICESLIST
 DROP CONSTRAINT FK_SERVICESLISTCAMPCARID
 DROP CONSTRAINT FK_SERVICESLISTSERVCENTERID
 DROP CONSTRAINT FK_SERVICESLISTRENTCOMPID
 DROP CONSTRAINT FK_SERVICESLISTCUSLICNUM;
